remote_theme: pmarsceill/just-the-docs

title: API Principles
description: The SBB API Principles [Draft]
baseurl: "/api-principles"
url: "https://schweizerischebundesbahnen.github.io"

permalink: pretty
search_enabled: true
heading_anchors: true
aux_links:
    "API Principles on GitHub":
      - "//github.com/schweizerischebundesbahnen/api-principles"
